services:
  client:
    build: .
    container_name: rksi_app_frontend
    ports:
      - '443:443'
    volumes:
      - './config:/config'
    restart: unless-stopped
  redirect:
    image: morbz/docker-web-redirect
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${APPLICATION_HOST}
      - REDIRECT_TARGET=${APPLICATION_HOST}:${APPLICATION_PORT}
    ports:
      - 80:80
