services:
  client:
    build: .
    container_name: rksi_app_frontend
    ports:
      - '443:443'
    volumes:
      - './config:/config'
      - './:/app/'
    env_file:
      - .env
    command: npm start