services:
  client:
    build: .
    container_name: rksi_app_frontend
    ports:
      - '${APPLICATION_HOST}:${APPLICATION_PORT}:3000'
    volumes:
      - './config:/config'
      - './src:/app/src'
    env_file:
      - .env
    command: npm start --port=3000